import type { MenuItem, Theme } from "@/types";

const LOCAL_DEMO_IMAGE = "/placeholder.svg";

export const baseThemes: Theme[] = [
  {
    id: "default",
    name: "Classic",
    primary: "hsl(var(--primary))",
    gradient: "linear-gradient(135deg, hsl(var(--primary)), hsl(var(--primary)) / 0.9)",
    accent: "hsl(var(--primary))"
  },
  {
    id: "warm",
    name: "Warm",
    primary: "#f97316",
    gradient: "linear-gradient(135deg, #f97316, #fb923c)",
    accent: "#f97316"
  },
  {
    id: "elegant",
    name: "Elegant",
    primary: "#6366f1",
    gradient: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    accent: "#7c3aed"
  },
  {
    id: "fresh",
    name: "Fresh",
    primary: "#10b981",
    gradient: "linear-gradient(135deg, #10b981, #34d399)",
    accent: "#10b981"
  },
  {
    id: "premium",
    name: "Premium",
    primary: "#f43f5e",
    gradient: "linear-gradient(135deg, #f43f5e, #fb7185)",
    accent: "#f43f5e"
  },
  {
    id: "dark",
    name: "Dark",
    primary: "#1e293b",
    gradient: "linear-gradient(135deg, #1e293b, #334155)",
    accent: "#475569"
  },
];

export const defaultItemsByServiceType: Record<string, MenuItem[]> = {
  restaurant: [
    {
      id: 1,
      name: "Smoked Lamb Ribs",
      description: "Fresh lamb ribs smoked on charcoal with rice and salad",
      price: "265",
      image: LOCAL_DEMO_IMAGE,
      category: "grill",
      featured: true,
      time: "25 min",
      rating: 4.8,
    },
    {
      id: 2,
      name: "Brisket Sandwich",
      description: "Grilled brisket with fresh veggies and special sauce",
      price: "210",
      image: LOCAL_DEMO_IMAGE,
      category: "sandwiches",
      featured: true,
      time: "15 min",
      rating: 4.9,
    },
    {
      id: 3,
      name: "Grilled Kebab Platter",
      description: "Fresh meat kebab with roasted potatoes and salad",
      price: "240",
      image: LOCAL_DEMO_IMAGE,
      category: "grill",
      featured: true,
      time: "20 min",
      rating: 4.7,
    },
    {
      id: 4,
      name: "Turkish Tea",
      description: "Authentic Turkish tea with mint and lemon",
      price: "25",
      image: LOCAL_DEMO_IMAGE,
      category: "drinks",
      time: "5 min",
      rating: 4.6,
    },
    {
      id: 5,
      name: "Fresh Cheesecake",
      description: "Creamy cheesecake with fresh berries",
      price: "85",
      image: LOCAL_DEMO_IMAGE,
      category: "desserts",
      time: "10 min",
      rating: 4.9,
    },
    {
      id: 6,
      name: "Classic Beef Burger",
      description: "Fresh beef burger with cheese, veggies and sauce",
      price: "180",
      image: LOCAL_DEMO_IMAGE,
      category: "sandwiches",
      time: "18 min",
      rating: 4.8,
    },
  ],
  cafe: [
    {
      id: 101,
      name: "Italian Espresso",
      description: "Strong and intense espresso from premium coffee beans",
      price: "35",
      image: LOCAL_DEMO_IMAGE,
      category: "hot",
      featured: true,
      time: "3 min",
      rating: 4.9,
    },
    {
      id: 102,
      name: "Creamy Cappuccino",
      description: "Cappuccino with creamy milk foam and cocoa",
      price: "45",
      image: LOCAL_DEMO_IMAGE,
      category: "hot",
      featured: true,
      time: "5 min",
      rating: 4.8,
    },
    {
      id: 103,
      name: "Vanilla Latte",
      description: "Latte with natural vanilla flavor",
      price: "50",
      image: LOCAL_DEMO_IMAGE,
      category: "hot",
      time: "6 min",
      rating: 4.7,
    },
    {
      id: 104,
      name: "Iced Coffee",
      description: "Cold coffee with milk and ice",
      price: "40",
      image: LOCAL_DEMO_IMAGE,
      category: "cold",
      featured: true,
      time: "4 min",
      rating: 4.8,
    },
    {
      id: 105,
      name: "Chocolate Frappuccino",
      description: "Cold blended coffee with chocolate and cream",
      price: "55",
      image: LOCAL_DEMO_IMAGE,
      category: "cold",
      time: "5 min",
      rating: 4.9,
    },
    {
      id: 106,
      name: "Chocolate Croissant",
      description: "Fresh croissant filled with dark chocolate",
      price: "30",
      image: LOCAL_DEMO_IMAGE,
      category: "desserts",
      time: "2 min",
      rating: 4.6,
    },
    {
      id: 107,
      name: "Berry Muffin",
      description: "Fresh muffin with blueberries and cream",
      price: "35",
      image: LOCAL_DEMO_IMAGE,
      category: "desserts",
      time: "2 min",
      rating: 4.7,
    },
    {
      id: 108,
      name: "Snack Mix",
      description: "Mix of nuts and dried fruits",
      price: "25",
      image: LOCAL_DEMO_IMAGE,
      category: "snacks",
      time: "1 min",
      rating: 4.5,
    },
  ],
  salon: [
    {
      id: 201,
      name: "Men's Haircut",
      description: "Professional haircut with styling and trimming",
      price: "120",
      image: LOCAL_DEMO_IMAGE,
      category: "haircut",
      featured: true,
      time: "30 min",
      rating: 4.8,
    },
    {
      id: 202,
      name: "Women's Haircut",
      description: "Professional cut and trim with care tips",
      price: "150",
      image: LOCAL_DEMO_IMAGE,
      category: "haircut",
      featured: true,
      time: "45 min",
      rating: 4.9,
    },
    {
      id: 203,
      name: "Hair Styling",
      description: "Professional styling with blow dryer and iron",
      price: "80",
      image: LOCAL_DEMO_IMAGE,
      category: "styling",
      time: "25 min",
      rating: 4.7,
    },
    {
      id: 204,
      name: "Full Hair Coloring",
      description: "Professional hair coloring with premium products",
      price: "350",
      image: LOCAL_DEMO_IMAGE,
      category: "coloring",
      featured: true,
      time: "90 min",
      rating: 4.8,
    },
    {
      id: 205,
      name: "Hair Treatment",
      description: "Deep treatment for damaged and stressed hair",
      price: "200",
      image: LOCAL_DEMO_IMAGE,
      category: "treatments",
      time: "60 min",
      rating: 4.9,
    },
    {
      id: 206,
      name: "Special Occasion Updo",
      description: "Professional hairstyle for special occasions",
      price: "100",
      image: LOCAL_DEMO_IMAGE,
      category: "styling",
      time: "40 min",
      rating: 4.8,
    },
  ],
  pharmacy: [
    {
      id: 301,
      name: "Paracetamol 500mg",
      description: "Pain reliever and fever reducer",
      price: "15",
      image: LOCAL_DEMO_IMAGE,
      category: "medicines",
      featured: true,
      rating: 4.7,
    },
    {
      id: 302,
      name: "Vitamin D3",
      description: "Dietary supplement Vitamin D3 1000 IU",
      price: "85",
      image: LOCAL_DEMO_IMAGE,
      category: "vitamins",
      featured: true,
      rating: 4.8,
    },
    {
      id: 303,
      name: "Face Moisturizer",
      description: "Daily moisturizing cream for sensitive skin",
      price: "120",
      image: LOCAL_DEMO_IMAGE,
      category: "cosmetics",
      time: "In Stock",
      rating: 4.6,
    },
    {
      id: 304,
      name: "Baby Shampoo",
      description: "Gentle chemical-free shampoo for babies",
      price: "45",
      image: LOCAL_DEMO_IMAGE,
      category: "baby",
      time: "In Stock",
      rating: 4.9,
    },
    {
      id: 305,
      name: "Omega 3",
      description: "Fish oil dietary supplement",
      price: "150",
      image: LOCAL_DEMO_IMAGE,
      category: "vitamins",
      rating: 4.7,
    },
    {
      id: 306,
      name: "Antibiotic",
      description: "Amoxicillin 500mg - Prescription required",
      price: "35",
      image: LOCAL_DEMO_IMAGE,
      category: "medicines",
      rating: 4.5,
    },
  ],
  store: [
    {
      id: 401,
      name: "Smartphone",
      description: "Smart phone with 6.7\" display and 108MP camera",
      price: "8500",
      image: LOCAL_DEMO_IMAGE,
      category: "electronics",
      featured: true,
      rating: 4.8,
    },
    {
      id: 402,
      name: "Cotton T-Shirt",
      description: "100% cotton t-shirt in multiple colors",
      price: "150",
      image: LOCAL_DEMO_IMAGE,
      category: "clothing",
      featured: true,
      rating: 4.6,
    },
    {
      id: 403,
      name: "Home Rug",
      description: "Premium rug made of natural wool",
      price: "1200",
      image: LOCAL_DEMO_IMAGE,
      category: "home",
      time: "In Stock",
      rating: 4.7,
    },
    {
      id: 404,
      name: "Football",
      description: "Professional football made of genuine leather",
      price: "250",
      image: LOCAL_DEMO_IMAGE,
      category: "sports",
      time: "In Stock",
      rating: 4.8,
    },
    {
      id: 405,
      name: "Wireless Headphones",
      description: "Bluetooth headphones with noise cancellation",
      price: "450",
      image: LOCAL_DEMO_IMAGE,
      category: "electronics",
      rating: 4.9,
    },
    {
      id: 406,
      name: "Classic Jeans",
      description: "Straight-cut denim jeans",
      price: "320",
      image: LOCAL_DEMO_IMAGE,
      category: "clothing",
      rating: 4.7,
    },
  ],
  clinic: [
    {
      id: 501,
      name: "General Consultation",
      description: "Comprehensive medical exam with a specialist",
      price: "200",
      image: LOCAL_DEMO_IMAGE,
      category: "consultation",
      featured: true,
      time: "30 min",
      rating: 4.9,
    },
    {
      id: 502,
      name: "Blood Pressure Check",
      description: "Blood pressure measurement with medical report",
      price: "50",
      image: LOCAL_DEMO_IMAGE,
      category: "examination",
      time: "10 min",
      rating: 4.7,
    },
    {
      id: 503,
      name: "Physical Therapy",
      description: "Physical therapy session for muscles and joints",
      price: "300",
      image: LOCAL_DEMO_IMAGE,
      category: "treatment",
      featured: true,
      time: "45 min",
      rating: 4.8,
    },
    {
      id: 504,
      name: "Complete Blood Test",
      description: "Full blood analysis with detailed report",
      price: "400",
      image: LOCAL_DEMO_IMAGE,
      category: "tests",
      time: "15 min",
      rating: 4.9,
    },
    {
      id: 505,
      name: "Dental Consultation",
      description: "Teeth and gum examination with a dentist",
      price: "150",
      image: LOCAL_DEMO_IMAGE,
      category: "consultation",
      time: "20 min",
      rating: 4.8,
    },
    {
      id: 506,
      name: "Eye Exam",
      description: "Comprehensive eye and vision examination",
      price: "180",
      image: LOCAL_DEMO_IMAGE,
      category: "examination",
      time: "25 min",
      rating: 4.7,
    },
  ],
};

// Service type configuration - icons stored as string identifiers to be mapped in component
export interface ServiceTypeConfig {
  id: string;
  name: string;
  iconName: "Flame" | "Coffee" | "Scissors" | "Pill" | "Store" | "Building2";
  categories: { id: string; name: string; icon: string }[];
  placeholder: string;
  itemLabel: string;
}

export const serviceTypesConfig: ServiceTypeConfig[] = [
  {
    id: "restaurant",
    name: "Restaurant",
    iconName: "Flame",
    categories: [
      { id: "all", name: "All", icon: "🍽️" },
      { id: "grill", name: "Grill", icon: "🔥" },
      { id: "sandwiches", name: "Sandwiches", icon: "🥪" },
      { id: "drinks", name: "Drinks", icon: "🥤" },
      { id: "desserts", name: "Desserts", icon: "🍰" },
    ],
    placeholder: "e.g. Grill House",
    itemLabel: "Dish",
  },
  {
    id: "cafe",
    name: "Cafe",
    iconName: "Coffee",
    categories: [
      { id: "all", name: "All", icon: "☕" },
      { id: "hot", name: "Hot", icon: "🔥" },
      { id: "cold", name: "Cold", icon: "🧊" },
      { id: "desserts", name: "Desserts", icon: "🍰" },
      { id: "snacks", name: "Snacks", icon: "🍪" },
    ],
    placeholder: "e.g. Urban Cafe",
    itemLabel: "Product",
  },
  {
    id: "salon",
    name: "Salon",
    iconName: "Scissors",
    categories: [
      { id: "all", name: "All", icon: "✂️" },
      { id: "haircut", name: "Haircuts", icon: "💇" },
      { id: "styling", name: "Styling", icon: "💆" },
      { id: "coloring", name: "Coloring", icon: "🎨" },
      { id: "treatments", name: "Treatments", icon: "✨" },
    ],
    placeholder: "e.g. Glamour Salon",
    itemLabel: "Service",
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    iconName: "Pill",
    categories: [
      { id: "all", name: "All", icon: "💊" },
      { id: "medicines", name: "Medicines", icon: "💉" },
      { id: "vitamins", name: "Vitamins", icon: "🧪" },
      { id: "cosmetics", name: "Cosmetics", icon: "🧴" },
      { id: "baby", name: "Baby Care", icon: "👶" },
    ],
    placeholder: "e.g. HealthPlus Pharmacy",
    itemLabel: "Product",
  },
  {
    id: "store",
    name: "Store",
    iconName: "Store",
    categories: [
      { id: "all", name: "All", icon: "🛍️" },
      { id: "electronics", name: "Electronics", icon: "📱" },
      { id: "clothing", name: "Clothing", icon: "👕" },
      { id: "home", name: "Home", icon: "🏠" },
      { id: "sports", name: "Sports", icon: "⚽" },
    ],
    placeholder: "e.g. TechZone Store",
    itemLabel: "Product",
  },
  {
    id: "clinic",
    name: "Clinic",
    iconName: "Building2",
    categories: [
      { id: "all", name: "All", icon: "🏥" },
      { id: "consultation", name: "Consultation", icon: "👨‍⚕️" },
      { id: "examination", name: "Examination", icon: "🔬" },
      { id: "treatment", name: "Treatment", icon: "💊" },
      { id: "tests", name: "Lab Tests", icon: "🧪" },
    ],
    placeholder: "e.g. CareFirst Clinic",
    itemLabel: "Service",
  },
];



