-- Migration: Add new client profile columns
-- Run this against the Supabase 'clients' table

ALTER TABLE clients ADD COLUMN IF NOT EXISTS role TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cover_url TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cover_gradient TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS tagline TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS timezone TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS theme_accent TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS profile_visibility TEXT DEFAULT 'private';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS social_links JSONB DEFAULT '{}';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS brand_colors TEXT[] DEFAULT '{}';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS avatar_style TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS avatar_seed TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS avatar_config JSONB;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS industry TEXT;